### ISSUE TITLE
Suspend / resume / rebuild support

### ISSUE THREAD

**Issue by ste78** [alces-software/cloudware#1]
So that we can use cloudware as a orchestration facility in metalware we should implement a method to spoof metals powering off/on/status as well as an installs ability to reformat the disks and redeploy. I’d suggest

power off -> shutdown instance but do not terminate 
power on -> resume instance 
power status -> report running state of instance as ON or OFF

rebuild -> recreate instance as if it had just been created with the ‘create’ command

**Comment by bobwhitelock** [comment]
This was allegedly fixed by https://github.com/alces-software/cloudware/pull/10, please reopen if anything still needs doing.
