### ISSUE TITLE
Allow Setting of IPs for FlightConnector Concept

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/cloudware#117]
Currently it's questionable how supported setting IP addresses and subnets for domain0 and domainU clusters. Investigate and fix this such that these can be customised (to partner with the flight-blueprint tool).

This will involve checking/changing/verifying: 
- Domain templates
- Machine templates
- Cloud-init userdata
- Any upstream scripts which are curled and run as part of the configuration process

Questions:
- How does this effect cluster_index?

**Comment by WilliamMcCumstie** [comment]
This issue is obsolete as it concerns the older version of cloudware
