### ISSUE TITLE
Allow to list machines for a domain name

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/cloudware#118]
The listing of machines doesn't seem to have a specific order of any kind so machines in the same domain are scattered across the table making it difficult to make out what is in a domain. If the `-d/--domain` flag could be passed to `fc machine list` it would make it a lot easier to see what machines are there.

**Comment by WilliamMcCumstie** [comment]
This issue is obsolete as it concerns the older version of cloudware
