### ISSUE TITLE
Allow recursive deletion of domain and machines within it

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/cloudware#119]
This is open for discussion.

I'm proposing that we should allow the deletion of a domain if it has machines in it. Currently there will be an error if attempting to delete a domain that has machines in.

Manually deleting every single machine with the cloudware CLI is time consuming so a `--delete-machines` option or some warning that needs to be explicitly agreed to in order to destroy the entirety of the domain and the machines within would be very helpful IMO.

**Comment by WilliamMcCumstie** [comment]
This issue is obsolete as it concerns the older version of cloudware
