### ISSUE TITLE
Rebrand main command line tool and refactor

### ISSUE THREAD

**Issue by ste78** [alces-software/cloudware#26]
# Main
Rename the main cloudware command to be `flightconnector` and rebrand the help text to match.

# Bonus
Whilst we're there, refactor command line usage to be user friendly, eg help when running the command with no options, displaying help. eg When doing things like this...

```
[root@controller[barkla] ~]# cloudware idunno --help
invalid command. Use --help for more information
```

Is not overly helpful. 

I think @ColonelPanicks may have some more opinions to add to this as well.

**Comment by ColonelPanicks** [comment]
Additional notes of pedantry and frustration:

- The command object isn't properly structured. Both `cloudware domain` and `cloudware machine` aren't actually seen as commands that have subcommands.

- CLI arguments aren't shared which (at least once based on what I've noticed/tweaked) has lead to inconsistencies in terms `provider` and `domain`. Sharing arguments would allow for better consistency.

**Comment by WilliamMcCumstie** [comment]
So the external rebranding is pretty straight forward. As far as `cloudware idunno --help` is concerned, we don't currently support that in metalware either:
```
[root@localhost ~]# metal idunno --help                                            
invalid command. Use --help for more information
```

Currently sub commands aren't working because the vanilla version of `Commander` is in use. I'll will be updating it to the `alces` version soon-ish.

**Comment by WilliamMcCumstie** [comment]
As far as the duplication in the `cli`, whilst there is room for improvement, it isn't worth fixing as the commands themselves are likely to change. This can be progressively fixed as the commands are refactored.
