### ISSUE TITLE
Refactor Machine to FlightConnect Cluster node types

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/cloudware#28]
Currently the machine types (currently referred to as `roles`) are `master` and `slave` which are sourced from `providers/aws/templates/machine-{master,slave}.yml`.

Ideally the types that would exist are `login`, `compute`, `storage` and `graphical`. 

- Templates to be put in place by *Stu* as `providers/aws/templates/machine-{login,compute,storage,graphical}/yml` 
- Command to be refactored to support varying types (note: this may be supported already if `role` is just looked for as `machine-ROLE.yml` in the CLI object)

Worth considering whether the machine type (VM instance size) is hardcoded or supplied from CLI.

**Comment by ColonelPanicks** [comment]
There most likely will be the requirement for slightly different AMIs depending on the machine role, especially in the case of the `login` node which would be ideal to have levels of automation to connect to FlightConnector Gateway.

**Comment by ste78** [comment]
I think we can start with just login and compute for now. I suggest our first pass on these does something like...

login:
- set hostname to be login1.<cloudconnector domain name>.alces.network
- installs the vpn client script via cloudinit

compute:
- sets hostname to be node[XX].<cloudconnector domain name>.alces.network with XX being automatically decided by the cloudconnector cli tool in sequence of starting.

**Comment by ColonelPanicks** [comment]
Merged #38, templates now available in `develop`

**Comment by ColonelPanicks** [comment]
Removing this from the 2018.1.0 project plan, enough of the templates are in to get the 2018.1.0 release ready to be tagged 'n' bagged

**Comment by WilliamMcCumstie** [comment]
This issue is obsolete as it concerns the older version of cloudware
