### ISSUE TITLE
Connector image and vpn setup cloudinit script aws & azure

### ISSUE THREAD

**Issue by ste78** [alces-software/cloudware#33]
Implement a Flight connector image build script (modify cloudware/support/build/alces-cloudware-base-aws.ks) to build a clean image and then make the changes required for vpn setup via cloudinit on boot. As started in #25 

Some of the things in the existing kickstart file can also be dropped (such as disabling firewalld, because we just enable it again in the build script.) Some of the install stages from the vpn init script can also be put in the kickstart, we only need to do the configuration / key generation parts via cloudinit.

**Comment by ColonelPanicks** [comment]
No longer 2018.1.0 milestone

**Comment by WilliamMcCumstie** [comment]
This issue is obsolete as it concerns the older version of cloudware
