### ISSUE TITLE
Remove redundant domain parameters

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/cloudware#53]
**This bug is not necessarily urgent and can be kicked down the road, it's just being logged here as a reminder to address at some point.**

Currently the domain0 and domainU templates have no use for the networkCidr and priSubnetCidr variables in their CloudFormation templates. These are still in place because cloudware looks to merge parameters into the template that include these variables.

Going forward it would be nice to remove these redundant parameters.

**Comment by WilliamMcCumstie** [comment]
This issue is obsolete as it concerns the older version of cloudware
