### ISSUE TITLE
Display public IP in machine list

### ISSUE THREAD

**Issue by mjtko** [alces-software/cloudware#69]
If a machine has a public IP, it would be useful to be able to display that information in the `machine list` output -- at the moment I have to go to the cloud provider console to work this out.

**Comment by ste78** [comment]
that used to be on machine info - have we lost that?

**Comment by mjtko** [comment]
Not sure, `machine info` isn't working at the moment. :)

**Comment by mjtko** [comment]
It's working again! Yes, that info is there. Still might be nice in the list tho.
