### ISSUE TITLE
Store more information about a machine

### ISSUE THREAD

**Issue by vlj91** [alces-software/cloudware#8]
Currently we're storing the following information about a machine in each provider:

* State
* External IP (if applicable)
* Prv and mgt IP
* Short hostname
* Flavour

We could also do with optionally storing:

* Instance ID if applicable based on the Cloud provider

**Comment by bobwhitelock** [comment]
This was allegedly fixed by https://github.com/alces-software/cloudware/pull/10, please reopen if anything still needs doing.
