### ISSUE TITLE
Domain Name Not Appended to Machine Name

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/cloudware#81]
If I create a domain:
```
[root@controller cloudware]# bin/cloud domain create -t domain0 --networkcidr 10.78.100.0/24 --prisubnetcidr 10.78.100.0/24 berserk-buzzard-dom0
[OK]  Creating new domain
```

And then create a machine within it:
```
[root@controller cloudware]# bin/cloud machine create -d berserk-buzzard-dom0 --role gateway --priip 10.78.100.10 gateway
[OK]  Creating new deployment
```

What I see (in CloudFormation) is:
<img width="539" alt="screen shot 2018-05-17 at 17 50 37" src="https://user-images.githubusercontent.com/27725639/40191976-f248a4e6-59fa-11e8-8518-432c97f7db8b.png">

Ideally the name would be `berserk-buzzard-dom0-gateway`.

**Comment by ColonelPanicks** [comment]
A major issue caused by this is that stack names are checked so that 'duplicates' are not created. This isn't helpful in the event that 2 different domains would have a machine named login (which they certainly will).

```
[root@controller cloudware]# bin/cloud machine create --domain berserk-buzzard-cluster1 --role login --cluster-index 1 --priip 10.100.1.10 login
[OK]  Creating new deployment
[root@controller cloudware]# bin/cloud machine create --domain berserk-buzzard-cluster2 --role login --cluster-index 2 --priip 10.100.2.10 login
[OK]  Creating new deployment
error: Stack [login] already exists. Use --trace to view backtrace
```

**Comment by WilliamMcCumstie** [comment]
This issue is obsolete as it concerns the older version of cloudware
