### ISSUE TITLE
Replace 'login' for DomU Machine Name

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/cloudware#83]
Azure does not allow the usage of 'login' in resource names with public-facing IPs. 

Find a synonym (`access`?) for login or some more appropriate way of naming it to replace the current workaround name `loogin`.

**Comment by ColonelPanicks** [comment]
Not `access` either, it's also reserved, thanks Microsoft - https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-reserved-resource-name

**Comment by WilliamMcCumstie** [comment]
This issue is obsolete as it concerns the older version of cloudware
