### ISSUE TITLE
Review the use of the `cloudware` tags

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/cloudware#92]
For both `aws` and `azure` the use of `cloudware_` tags has been a source of confusion. As they are only tags, they are not necessarily meaningful.

A prime example is the `cloudware_pri_subnet` usage in the `aws` templates. The tag is included in with the templates but is then subsequently not used. This means when downloading the domain information, it isn't immediately obvious where the subnet information is coming form.

In a similar vein, the `cloudware_domain` tag ins't particularly useful either. `Domains` have a name parameter which is being duplicated by the `cloudware_domain` field. However it is the field that is required to be unique and thus is more important.

Ideally, the usage of the tags should be limited to the bear minimum and instead the properties of the resource should be used to populate the model information.

**Comment by ColonelPanicks** [comment]
This issue is obsolete as it concerns the older version of cloudware
